package org.sensepitch.edge;

/**
 * @author Jens Wilke
 */
public class TimeBasedChallengeString implements ChallengeStringGenerator {

  static int VERIFY_RANGE_MINUTES = 5;
  static long VERIFY_RANGE = 1000 * 60 * VERIFY_RANGE_MINUTES;
  static int RADIX = 23;

  @Override
  public String generateChallenge() {
    return generateChallengeString();
  }

  @Override
  public long verifyChallenge(String challenge) {
    return verifyChallengeString(challenge);
  }

  public static String generateChallengeString() {
    return generateChallengeString(System.currentTimeMillis());
  }

  public static String generateChallengeString(long t) {
    return Long.toString(t, RADIX);
  }

  public static long verifyChallengeString(String challengeString, long now) {
    if (challengeString.isEmpty() || challengeString.length() > 15 ) {
      return 0;
    }
    try {
      long t = Long.parseLong(challengeString, RADIX);
      if (now == 0) {
        now = System.currentTimeMillis();
      }
      if (Math.abs(now - t) < VERIFY_RANGE) {
        return t;
      }
    } catch (NumberFormatException e) {
      // ignore
    }
    return 0;
  }

  /**
   * Check whether the challenge was generated by us. We only check whether it is within the
   * {@code VERIFY_RANGE_MINUTES} minutes server time span, to avoid prerecorded results.
   */
  public static long verifyChallengeString(String challengeString) {
    return verifyChallengeString(challengeString, 0);
  }

}
